# Form implementation generated from reading ui file 'chi_tiet_san_pham.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_chitietsanpham(object):
    def setupUi(self, chitietsanpham):
        chitietsanpham.setObjectName("chitietsanpham")
        chitietsanpham.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=chitietsanpham)
        self.centralwidget.setObjectName("centralwidget")
        self.but_bom = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_bom.setGeometry(QtCore.QRect(10, 20, 120, 35))
        self.but_bom.setObjectName("but_bom")
        self.but_tailieu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_tailieu.setGeometry(QtCore.QRect(140, 20, 120, 35))
        self.but_tailieu.setObjectName("but_tailieu")
        self.but_53 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_53.setGeometry(QtCore.QRect(270, 20, 120, 35))
        self.but_53.setText("")
        self.but_53.setObjectName("but_53")
        self.but_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_back.setGeometry(QtCore.QRect(400, 20, 120, 35))
        self.but_back.setObjectName("but_back")
        self.lable_sp = QtWidgets.QLabel(parent=self.centralwidget)
        self.lable_sp.setGeometry(QtCore.QRect(20, 70, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lable_sp.setFont(font)
        self.lable_sp.setObjectName("lable_sp")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(680, 10, 111, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 60, 101, 31))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 130, 781, 381))
        self.textEdit.setObjectName("textEdit")
        self.but_chinhsua_thongtin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_chinhsua_thongtin.setGeometry(QtCore.QRect(350, 520, 111, 41))
        self.but_chinhsua_thongtin.setObjectName("but_chinhsua_thongtin")
        chitietsanpham.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=chitietsanpham)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuS_n_ph_m = QtWidgets.QMenu(parent=self.menubar)
        self.menuS_n_ph_m.setObjectName("menuS_n_ph_m")
        chitietsanpham.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=chitietsanpham)
        self.statusbar.setObjectName("statusbar")
        chitietsanpham.setStatusBar(self.statusbar)
        self.action_sanphammoi = QtGui.QAction(parent=chitietsanpham)
        self.action_sanphammoi.setObjectName("action_sanphammoi")
        self.action_sanpham = QtGui.QAction(parent=chitietsanpham)
        self.action_sanpham.setObjectName("action_sanpham")
        self.action_linhkien1 = QtGui.QAction(parent=chitietsanpham)
        self.action_linhkien1.setObjectName("action_linhkien1")
        self.actionK_ho_ch_SX = QtGui.QAction(parent=chitietsanpham)
        self.actionK_ho_ch_SX.setObjectName("actionK_ho_ch_SX")
        self.actionL_nh_s_n_xu_t = QtGui.QAction(parent=chitietsanpham)
        self.actionL_nh_s_n_xu_t.setObjectName("actionL_nh_s_n_xu_t")
        self.actionTest_QC = QtGui.QAction(parent=chitietsanpham)
        self.actionTest_QC.setObjectName("actionTest_QC")
        self.actionNh_p_kho = QtGui.QAction(parent=chitietsanpham)
        self.actionNh_p_kho.setObjectName("actionNh_p_kho")
        self.actionXu_t_kho = QtGui.QAction(parent=chitietsanpham)
        self.actionXu_t_kho.setObjectName("actionXu_t_kho")
        self.action_t_h_ng_linh_ki_n = QtGui.QAction(parent=chitietsanpham)
        self.action_t_h_ng_linh_ki_n.setObjectName("action_t_h_ng_linh_ki_n")
        self.actionLinh_ki_n_t_n_kho = QtGui.QAction(parent=chitietsanpham)
        self.actionLinh_ki_n_t_n_kho.setObjectName("actionLinh_ki_n_t_n_kho")
        self.actionB_o_gi = QtGui.QAction(parent=chitietsanpham)
        self.actionB_o_gi.setObjectName("actionB_o_gi")
        self.action_n_t_h_ng = QtGui.QAction(parent=chitietsanpham)
        self.action_n_t_h_ng.setObjectName("action_n_t_h_ng")
        self.actionS_n_ph_m_b_o_h_nh = QtGui.QAction(parent=chitietsanpham)
        self.actionS_n_ph_m_b_o_h_nh.setObjectName("actionS_n_ph_m_b_o_h_nh")
        self.actionDanh_s_ch_kh_ch_h_ng = QtGui.QAction(parent=chitietsanpham)
        self.actionDanh_s_ch_kh_ch_h_ng.setObjectName("actionDanh_s_ch_kh_ch_h_ng")
        self.actionH_ng_d_n_c_i_t = QtGui.QAction(parent=chitietsanpham)
        self.actionH_ng_d_n_c_i_t.setObjectName("actionH_ng_d_n_c_i_t")
        self.actionH_ng_d_n_s_d_ng = QtGui.QAction(parent=chitietsanpham)
        self.actionH_ng_d_n_s_d_ng.setObjectName("actionH_ng_d_n_s_d_ng")
        self.actionUpdate = QtGui.QAction(parent=chitietsanpham)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionK_t_th_c = QtGui.QAction(parent=chitietsanpham)
        self.actionK_t_th_c.setObjectName("actionK_t_th_c")
        self.menuS_n_ph_m.addAction(self.action_sanphammoi)
        self.menuS_n_ph_m.addAction(self.action_sanpham)
        self.menuS_n_ph_m.addSeparator()
        self.menuS_n_ph_m.addAction(self.action_linhkien1)
        self.menuS_n_ph_m.addSeparator()
        self.menuS_n_ph_m.addAction(self.actionK_t_th_c)
        self.menubar.addAction(self.menuS_n_ph_m.menuAction())

        self.retranslateUi(chitietsanpham)
        QtCore.QMetaObject.connectSlotsByName(chitietsanpham)

    def retranslateUi(self, chitietsanpham):
        _translate = QtCore.QCoreApplication.translate
        chitietsanpham.setWindowTitle(_translate("chitietsanpham", "Chi tiết sản phẩm"))
        self.but_bom.setText(_translate("chitietsanpham", "BOM list"))
        self.but_tailieu.setText(_translate("chitietsanpham", "Tài liệu"))
        self.but_back.setText(_translate("chitietsanpham", "Back"))
        self.lable_sp.setText(_translate("chitietsanpham", "Thông tin sản phẩm"))
        self.label.setText(_translate("chitietsanpham", "Username"))
        self.label_2.setText(_translate("chitietsanpham", "Date"))
        self.textEdit.setHtml(_translate("chitietsanpham", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ghi thông tin mô tả sản phẩm</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Những User được phân quyền có thể chỉnh sửa:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Bom list</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Mô tả sản phẩm</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Quản lý tài liệu kèm theo sản phẩm</p></body></html>"))
        self.but_chinhsua_thongtin.setText(_translate("chitietsanpham", "Chỉnh sửa thông tin"))
        self.menuS_n_ph_m.setTitle(_translate("chitietsanpham", "Sản phẩm"))
        self.action_sanphammoi.setText(_translate("chitietsanpham", "Sản phẩm mới"))
        self.action_sanpham.setText(_translate("chitietsanpham", "Danh sách sản phẩm"))
        self.action_linhkien1.setText(_translate("chitietsanpham", "Linh kiện"))
        self.actionK_ho_ch_SX.setText(_translate("chitietsanpham", "Kế hoạch SX"))
        self.actionL_nh_s_n_xu_t.setText(_translate("chitietsanpham", "Lệnh sản xuất"))
        self.actionTest_QC.setText(_translate("chitietsanpham", "Test QC"))
        self.actionNh_p_kho.setText(_translate("chitietsanpham", "Nhập kho"))
        self.actionXu_t_kho.setText(_translate("chitietsanpham", "Xuất kho"))
        self.action_t_h_ng_linh_ki_n.setText(_translate("chitietsanpham", "Đặt hàng linh kiện"))
        self.actionLinh_ki_n_t_n_kho.setText(_translate("chitietsanpham", "Linh kiện tồn kho"))
        self.actionB_o_gi.setText(_translate("chitietsanpham", "Báo giá"))
        self.action_n_t_h_ng.setText(_translate("chitietsanpham", "Đơn đặt hàng"))
        self.actionS_n_ph_m_b_o_h_nh.setText(_translate("chitietsanpham", "Sản phẩm bảo hành"))
        self.actionDanh_s_ch_kh_ch_h_ng.setText(_translate("chitietsanpham", "Danh sách khách hàng"))
        self.actionH_ng_d_n_c_i_t.setText(_translate("chitietsanpham", "Hướng dẫn cài đặt"))
        self.actionH_ng_d_n_s_d_ng.setText(_translate("chitietsanpham", "Hướng dẫn sử dụng"))
        self.actionUpdate.setText(_translate("chitietsanpham", "Update"))
        self.actionK_t_th_c.setText(_translate("chitietsanpham", "Kết thúc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    chitietsanpham = QtWidgets.QMainWindow()
    ui = Ui_chitietsanpham()
    ui.setupUi(chitietsanpham)
    chitietsanpham.show()
    sys.exit(app.exec())
