# Form implementation generated from reading ui file 'san_pham_moi.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_sanphammoi(object):
    def setupUi(self, sanphammoi):
        sanphammoi.setObjectName("sanphammoi")
        sanphammoi.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=sanphammoi)
        self.centralwidget.setObjectName("centralwidget")
        self.but_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_save.setEnabled(True)
        self.but_save.setGeometry(QtCore.QRect(10, 20, 120, 35))
        self.but_save.setObjectName("but_save")
        self.but_tailieu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_tailieu.setEnabled(False)
        self.but_tailieu.setGeometry(QtCore.QRect(140, 20, 120, 35))
        self.but_tailieu.setObjectName("but_tailieu")
        self.but_bom = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_bom.setEnabled(False)
        self.but_bom.setGeometry(QtCore.QRect(270, 20, 120, 35))
        self.but_bom.setObjectName("but_bom")
        self.but_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_back.setGeometry(QtCore.QRect(400, 20, 120, 35))
        self.but_back.setObjectName("but_back")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(680, 10, 111, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 34, 101, 31))
        self.label_2.setObjectName("label_2")
        self.text_mo_ta_sp = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_mo_ta_sp.setGeometry(QtCore.QRect(10, 160, 781, 341))
        self.text_mo_ta_sp.setObjectName("text_mo_ta_sp")
        self.text_model = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_model.setGeometry(QtCore.QRect(10, 70, 151, 31))
        self.text_model.setObjectName("text_model")
        self.text_ten_sp = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_ten_sp.setGeometry(QtCore.QRect(10, 110, 781, 31))
        self.text_ten_sp.setObjectName("text_ten_sp")
        self.text_version = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_version.setGeometry(QtCore.QRect(170, 70, 161, 31))
        self.text_version.setObjectName("text_version")
        sanphammoi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=sanphammoi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuS_n_ph_m = QtWidgets.QMenu(parent=self.menubar)
        self.menuS_n_ph_m.setObjectName("menuS_n_ph_m")
        sanphammoi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=sanphammoi)
        self.statusbar.setObjectName("statusbar")
        sanphammoi.setStatusBar(self.statusbar)
        self.action_sanphammoi = QtGui.QAction(parent=sanphammoi)
        self.action_sanphammoi.setObjectName("action_sanphammoi")
        self.action_sanpham = QtGui.QAction(parent=sanphammoi)
        self.action_sanpham.setObjectName("action_sanpham")
        self.action_linhkien1 = QtGui.QAction(parent=sanphammoi)
        self.action_linhkien1.setObjectName("action_linhkien1")
        self.actionK_ho_ch_SX = QtGui.QAction(parent=sanphammoi)
        self.actionK_ho_ch_SX.setObjectName("actionK_ho_ch_SX")
        self.actionL_nh_s_n_xu_t = QtGui.QAction(parent=sanphammoi)
        self.actionL_nh_s_n_xu_t.setObjectName("actionL_nh_s_n_xu_t")
        self.actionTest_QC = QtGui.QAction(parent=sanphammoi)
        self.actionTest_QC.setObjectName("actionTest_QC")
        self.actionNh_p_kho = QtGui.QAction(parent=sanphammoi)
        self.actionNh_p_kho.setObjectName("actionNh_p_kho")
        self.actionXu_t_kho = QtGui.QAction(parent=sanphammoi)
        self.actionXu_t_kho.setObjectName("actionXu_t_kho")
        self.action_t_h_ng_linh_ki_n = QtGui.QAction(parent=sanphammoi)
        self.action_t_h_ng_linh_ki_n.setObjectName("action_t_h_ng_linh_ki_n")
        self.actionLinh_ki_n_t_n_kho = QtGui.QAction(parent=sanphammoi)
        self.actionLinh_ki_n_t_n_kho.setObjectName("actionLinh_ki_n_t_n_kho")
        self.actionB_o_gi = QtGui.QAction(parent=sanphammoi)
        self.actionB_o_gi.setObjectName("actionB_o_gi")
        self.action_n_t_h_ng = QtGui.QAction(parent=sanphammoi)
        self.action_n_t_h_ng.setObjectName("action_n_t_h_ng")
        self.actionS_n_ph_m_b_o_h_nh = QtGui.QAction(parent=sanphammoi)
        self.actionS_n_ph_m_b_o_h_nh.setObjectName("actionS_n_ph_m_b_o_h_nh")
        self.actionDanh_s_ch_kh_ch_h_ng = QtGui.QAction(parent=sanphammoi)
        self.actionDanh_s_ch_kh_ch_h_ng.setObjectName("actionDanh_s_ch_kh_ch_h_ng")
        self.actionH_ng_d_n_c_i_t = QtGui.QAction(parent=sanphammoi)
        self.actionH_ng_d_n_c_i_t.setObjectName("actionH_ng_d_n_c_i_t")
        self.actionH_ng_d_n_s_d_ng = QtGui.QAction(parent=sanphammoi)
        self.actionH_ng_d_n_s_d_ng.setObjectName("actionH_ng_d_n_s_d_ng")
        self.actionUpdate = QtGui.QAction(parent=sanphammoi)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionK_t_th_c = QtGui.QAction(parent=sanphammoi)
        self.actionK_t_th_c.setObjectName("actionK_t_th_c")
        self.menuS_n_ph_m.addAction(self.action_sanphammoi)
        self.menuS_n_ph_m.addAction(self.action_sanpham)
        self.menuS_n_ph_m.addSeparator()
        self.menuS_n_ph_m.addAction(self.action_linhkien1)
        self.menuS_n_ph_m.addSeparator()
        self.menuS_n_ph_m.addAction(self.actionK_t_th_c)
        self.menubar.addAction(self.menuS_n_ph_m.menuAction())

        self.retranslateUi(sanphammoi)
        QtCore.QMetaObject.connectSlotsByName(sanphammoi)

    def retranslateUi(self, sanphammoi):
        _translate = QtCore.QCoreApplication.translate
        sanphammoi.setWindowTitle(_translate("sanphammoi", "Tạo sản phẩm mới"))
        self.but_save.setText(_translate("sanphammoi", "Save"))
        self.but_tailieu.setText(_translate("sanphammoi", "Tài liệu"))
        self.but_bom.setText(_translate("sanphammoi", "BOM list"))
        self.but_back.setText(_translate("sanphammoi", "Back"))
        self.label.setText(_translate("sanphammoi", "Username"))
        self.label_2.setText(_translate("sanphammoi", "Date"))
        self.text_mo_ta_sp.setHtml(_translate("sanphammoi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ghi thông tin mô tả sản phẩm</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Chỉ những user được phân quyền mới có thể thêm sản phẩm mới lên hệ thống</p></body></html>"))
        self.text_model.setHtml(_translate("sanphammoi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Model</p></body></html>"))
        self.text_ten_sp.setWhatsThis(_translate("sanphammoi", "Nhập tên sản phẩm, không bao gồm model"))
        self.text_ten_sp.setHtml(_translate("sanphammoi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Tên sản phẩm</p></body></html>"))
        self.text_version.setHtml(_translate("sanphammoi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version</p></body></html>"))
        self.menuS_n_ph_m.setTitle(_translate("sanphammoi", "Sản phẩm"))
        self.action_sanphammoi.setText(_translate("sanphammoi", "Sản phẩm mới"))
        self.action_sanpham.setText(_translate("sanphammoi", "Danh sách sản phẩm"))
        self.action_linhkien1.setText(_translate("sanphammoi", "Linh kiện"))
        self.actionK_ho_ch_SX.setText(_translate("sanphammoi", "Kế hoạch SX"))
        self.actionL_nh_s_n_xu_t.setText(_translate("sanphammoi", "Lệnh sản xuất"))
        self.actionTest_QC.setText(_translate("sanphammoi", "Test QC"))
        self.actionNh_p_kho.setText(_translate("sanphammoi", "Nhập kho"))
        self.actionXu_t_kho.setText(_translate("sanphammoi", "Xuất kho"))
        self.action_t_h_ng_linh_ki_n.setText(_translate("sanphammoi", "Đặt hàng linh kiện"))
        self.actionLinh_ki_n_t_n_kho.setText(_translate("sanphammoi", "Linh kiện tồn kho"))
        self.actionB_o_gi.setText(_translate("sanphammoi", "Báo giá"))
        self.action_n_t_h_ng.setText(_translate("sanphammoi", "Đơn đặt hàng"))
        self.actionS_n_ph_m_b_o_h_nh.setText(_translate("sanphammoi", "Sản phẩm bảo hành"))
        self.actionDanh_s_ch_kh_ch_h_ng.setText(_translate("sanphammoi", "Danh sách khách hàng"))
        self.actionH_ng_d_n_c_i_t.setText(_translate("sanphammoi", "Hướng dẫn cài đặt"))
        self.actionH_ng_d_n_s_d_ng.setText(_translate("sanphammoi", "Hướng dẫn sử dụng"))
        self.actionUpdate.setText(_translate("sanphammoi", "Update"))
        self.actionK_t_th_c.setText(_translate("sanphammoi", "Kết thúc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sanphammoi = QtWidgets.QMainWindow()
    ui = Ui_sanphammoi()
    ui.setupUi(sanphammoi)
    sanphammoi.show()
    sys.exit(app.exec())
